# Комментарии к предложениям
## Создание комментария
POST http://localhost:4000/offers/665628a9036ca9de0c3b4ce7/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjYzOWZmMDQ4NjY3OWYwY2ZkOGU1N2QwIiwiaWF0IjoxNzE2ODE1NzEzLCJleHAiOjE3MTY5ODg1MTN9.yRdSsJveWp2Rc3opTRRtiWIINhCslPVN8-dUpvN8L0I

{
    "comment": "Супер",
    "rating": 3,
    "offerId": "665628a9036ca9de0c3b4ce7",
    "userId": "6639ff0486679f0cfd8e57d0"
}

###
